version: "2"
services:
  ruby-3.0:
    build: 
      context: ./
      dockerfile: Dockerfile.alpine
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: rnds/ruby:3.0
    working_dir: /home/app
    
  ruby-3.0-debian:
    build:
      context: ./
      dockerfile: Dockerfile.debian
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: rnds/ruby:3.0-debian
    working_dir: /home/app
    


