version: "2"
services:
  passenger-2.3:
    extends:
      file: 2.3/docker-compose.yml
      service: passenger-2.3

  passenger-2.3-cap:
    extends:
      file: 2.3/cap/docker-compose.yml
      service: passenger-2.3-cap
    depends_on:
      - passenger-2.3
    
  passenger-2.3-gen:
    extends:
      file: 2.3/cap/gen/docker-compose.yml
      service: passenger-2.3-gen
    depends_on:
      - passenger-2.3-cap
    

  passenger-2.6:
    extends:
      file: 2.6/docker-compose.yml
      service: passenger-2.6

  passenger-2.6-cap:
    extends:
      file: 2.6/cap/docker-compose.yml
      service: passenger-2.6-cap
    depends_on:
      - passenger-2.6
    
  passenger-2.6-gen:
    extends:
      file: 2.6/cap/gen/docker-compose.yml
      service: passenger-2.6-gen
    depends_on:
      - passenger-2.6-cap
    

  passenger-slim:
    extends:
      file: slim/docker-compose.yml
      service: passenger-slim

  passenger-slim-build:
    extends:
      file: slim/build/docker-compose.yml
      service: passenger-slim-build
    depends_on:
      - passenger-slim
