version: "2"
services:
  ruby-2.3.0:
    extends:
      file: rnds/ruby/2.3.0/docker-compose.yml
      service: ruby-2.3.0

  ruby-2.3.0-test:
    extends:
      file: rnds/ruby/2.3.0/test/docker-compose.yml
      service: ruby-2.3.0-test
    depends_on:
      - ruby-2.3.0

  passenger-2.3:
    extends:
      file: rnds/passenger/2.3/docker-compose.yml
      service: passenger-2.3
    


