version: "2.3"
services:
  ruby-2.5-pdf:
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        PRIVATE_REPO: ${PRIVATE_REPO-http://nexus.rnds.local/repository/internal}
    image: rnds/rubypdf:2.5
    working_dir: /home/app
    


